### ISSUE TITLE
On ae dev it is not possible to delete an idea, ideasketch, proposal or ideasketcharchived

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#107]
this seems to be a database problem, as this does not happen with sqlite, needs further investigation

**Comment by fuzzylogic2000** [comment]
With postgres intstalled locally, I can reproduce that:
I cannot delete a proposal and the corresponding idea, ideasketch or ideasketcharchived.
But I can delete both an idea or an ideasketch when no corresponding proposal exists.

**Comment by fuzzylogic2000** [comment]
This seems to be quite complicated. The default behaviour for all our multi-table inheritance and the one-to-one-relation, we added ourself would be on_delete=model.CASCADE. When we only have Idea, and IdeaSketch this works in both directions, so by deleting the idea, the sketch is also deleted and vice versa. But the whole relation between all four models seems to be to complicated. 
Idea----------
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp; _Multi-table inheritance (implicit one-to-one)_
| &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |
Proposal &nbsp;&nbsp; IdeaSketch
|
| &nbsp;&nbsp; _OneToOne_
|
IdeaSketchArchived

Also, do we want to have everything else also deleted, once a proposal is deleted? Probably not?
