### ISSUE TITLE
error notification when using social login with google

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#111]
An error notification appears when I want to use the social login with google. 
I am signed in in google. Then choose the social login on ae-dev. then an error notification appears, saying that I am not logged in. 
However, I am logged in.

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld Is that still a problem? It works for me.

**Comment by gereonrahnfeld** [comment]
Works again. I forgot about this issue. Will close it.
