### ISSUE TITLE
content not clear in idea sketch wizard

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#112]
the following questions are not clear for me in the idea sketch wizard:

1. Idea topics other (idea details)
2. Year of registration (applicant section)

perhaps double check with MitOst if they really want to have these formulations?

**Comment by rukala** [comment]
@gereonrahnfeld : Idea topic other enables user to state topics that aren't in the list - I agree that a help text is needed here - we can pass this feedback to MitOst. The year of registration refers to the organisation that is applying - here too a help text would clarify that.

**Comment by slomo** [comment]
So no issue from our side, therefore closing.
