### ISSUE TITLE
image uploaded upside down

### ISSUE THREAD

**Issue by rukala** [liqd/a4-advocate-europe#114]
When I uploaded an image in the full proposal it appeared upside down in the 
![bildschirmfoto 2017-06-02 um 10 36 58](https://cloud.githubusercontent.com/assets/11075214/26717927/6ff381b6-477f-11e7-840f-67ff389d006b.png)
proposal detail view. The image is in the correct position on my computer.

**Comment by MagdaN** [comment]
This did not happen again and could not been reproduced. Closing for now.
