### ISSUE TITLE
Countries of partner organisations in German

### ISSUE THREAD

**Issue by rukala** [liqd/a4-advocate-europe#116]
I wrote a similar issue recently about the language in which the countries appear in the idea sketch form and you informed me that this is due to the system language of my browser. Can we determine that only English country names are shown?
Otherwise we have inconsistencies such as the one attached in the "creators" tab where everything but the country names are in English :)
<img width="285" alt="bildschirmfoto 2017-06-02 um 11 02 31" src="https://cloud.githubusercontent.com/assets/11075214/26719052/5d401e9a-4783-11e7-9f32-ece6871790d6.png">

**Comment by fuzzylogic2000** [comment]
That's ok for now.
