### ISSUE TITLE
Generally, it’s best to define choices inside a model class

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#148]
https://docs.djangoproject.com/en/1.11/ref/models/fields/#choices

Do we want that? Do we need that?

**Comment by slomo** [comment]
Sure looks nicer, but probably not high prio. We could also wrap them in enums.

**Comment by fuzzylogic2000** [comment]
Let's do that for new choices and leave the old ones like that?!
