### ISSUE TITLE
change of idea affiliation is not shown

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#151]
There is a problem when I want to change the idea affiliation of a user. Although the User accepted the invite to become a collaborator (in this case: gereon.rahnfeld@liqd.de) it is still stated that User has not accepted the invite, yet. 

![remove](https://user-images.githubusercontent.com/15954895/28025975-11e8e1cc-6595-11e7-8030-29f43df3ca33.png)

**Comment by slomo** [comment]
Can you provide a link? Does the user show as collaborator on the idea detail view.

**Comment by gereonrahnfeld** [comment]
here is the link: https://ae-dev.liqd.net/de/ideas/safari/edit/5/

the User doesn't show as collaborator on the idea detail view. The only collaborator who is shown is named: safari safari

**Comment by gereonrahnfeld** [comment]
seems to be solved
I close the issue
