### ISSUE TITLE
Symbols of activities with activity feed seem not to be centred

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#162]
The blue symbols in the grey boxes of the activity feed seem not to be centred. 

![activity feed signs](https://user-images.githubusercontent.com/15954895/28124261-757b240e-6723-11e7-87cf-df996a69aefb.png)

**Comment by mkind** [comment]
![](https://media.giphy.com/media/xT1ksK7W5KS3e/giphy.gif)

I am innocent. It's the CSS :smile:
