### ISSUE TITLE
When clicking on visit your idea sketch it shows me an error 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#164]
After I submitted a full proposal (+3) I wanted to click the link in the confirmation email. Instead of transferring me to the proposal detail page it showed me an error. 

![page cannot be found](https://user-images.githubusercontent.com/15954895/28128591-815fe22a-6730-11e7-99ea-a5c5b12066ed.png)

**Comment by fuzzylogic2000** [comment]
Arrgh, the actions do not work well with our momos. In the user profile, the action "added IdeaSketch" is later changed to "added Proposal" as soon as a proposal is added. And the action object in the notification email does not know its title and can't get its url.
