### ISSUE TITLE
activity feed only shows me latest five activities

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#165]
The activity feed only displays the latest five activities. There is no possibility to scroll down and access the activities before. 

![only 5 activities](https://user-images.githubusercontent.com/15954895/28128697-df330832-6730-11e7-9af5-c017d9c3658a.png)

**Comment by slomo** [comment]
As discussed in [zeplin]( https://app.zeplin.io/project/58affefed5db33e792721d40/screen/5910857760398b4ddf1c99b7) we should show a fixed number of 10 activities.

**Comment by gereonrahnfeld** [comment]
alright - ten activities sound good. Still only 5 at the moment.
