### ISSUE TITLE
in chrome and safari the arrow design fails 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#166]
The arrow is displayed as too short in both chrome and safari.

![chrome arrow design](https://user-images.githubusercontent.com/15954895/28128981-e50a0fca-6731-11e7-8200-67b70deb203e.png)

**Comment by fuzzylogic2000** [comment]
should be fixed with #184 - check!

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld checked and it looks fine now!
