### ISSUE TITLE
Position of filters and sorting in User Profile should be adjusted

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#170]
The filter as well as the sorting in the User Profile should be adjusted to the edge of the idea-tiles. There is a small gap right now. 

![user profile styling i](https://user-images.githubusercontent.com/15954895/28156153-d6e22240-67b1-11e7-99ae-8cc0565ad5a0.png)

![user profile styling ii](https://user-images.githubusercontent.com/15954895/28156156-d9960cea-67b1-11e7-8923-4ed467b40628.png)

**Comment by fuzzylogic2000** [comment]
fixed by #181
