### ISSUE TITLE
List of collaborators in the wizard should be flush-left

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#176]
![collaborators not aligned](https://user-images.githubusercontent.com/15954895/28160095-6eaab670-67bf-11e7-8fc0-9e4a0053d94a.png)

**Comment by slomo** [comment]
This is due to user having no avatar, which will be fixed with the introduction of default avatars.

**Comment by fuzzylogic2000** [comment]
fixed by #192
