### ISSUE TITLE
responsive design for pending invitation doesn't work

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#179]
When I invite a collaborator and the invitation is still pending the responsive design doesn't work on a small screen - the word removed is not readable anymore. 

![small screen](https://user-images.githubusercontent.com/15954895/28161142-b052268c-67c2-11e7-8618-e88cb633a251.png)

**Comment by fuzzylogic2000** [comment]
fixed by #189
