### ISSUE TITLE
hero image on landing page not matching the design

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#210]
mitost has some inspiring portrait photographs that will be used as hero image. 
We've never really talked about the mobile design for this one. Sorry… if you're unhappy please yell at me

![bildschirmfoto 2017-07-25 um 11 01 05](https://user-images.githubusercontent.com/22769111/28564219-9a40c852-7128-11e7-9900-79e640861103.png)
![bildschirmfoto 2017-07-25 um 11 00 57](https://user-images.githubusercontent.com/22769111/28564218-9a3deee8-7128-11e7-9076-048cd9bd6736.png)

Zeplin: https://zpl.io/Z16Pk0x

**Comment by damusp** [comment]
related to #202 ?

**Comment by MagdaN** [comment]
@damusp can you upload the designs for mobile to zeplin please?

**Comment by damusp** [comment]
ok, both designs are now on zeplin!

**Comment by fuzzylogic2000** [comment]
partly solved by #237 - the text is sometimes aligned left instead of centered now?

**Comment by damusp** [comment]
ah @fuzzylogic2000, thanks for pointing it out, I didn't pay enough attention to that. 
The hero text is left aligned on desktop for aesthetic reasons, but on mobile it doesnt make much sense. Everything can stay centered there!
