### ISSUE TITLE
Text on call to action

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#211]
Text on blue is always supposed to be white

<img width="493" alt="bildschirmfoto 2017-07-25 um 10 23 31" src="https://user-images.githubusercontent.com/22769111/28564382-1ffa99be-7129-11e7-869d-37350154be91.png">

**Comment by damusp** [comment]
The magnifing glass icon should also be white on blue. 

<img width="327" alt="bildschirmfoto 2017-07-25 um 11 22 31" src="https://user-images.githubusercontent.com/22769111/28565123-8e47cd40-712b-11e7-9e88-0b37a2c6063d.png">

**Comment by fuzzylogic2000** [comment]
Fixed in #237
