### ISSUE TITLE
Idea detail box corners

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#212]
These corners are supposed to have a border radius of 5px. 

Also, the drop shadow at the bottom corners behaves odd. Can this be improved?

<img width="330" alt="bildschirmfoto 2017-07-25 um 10 22 12" src="https://user-images.githubusercontent.com/22769111/28564546-98cc1f48-7129-11e7-8e71-648e6d300c52.png">
<img width="500" alt="bildschirmfoto 2017-07-25 um 10 22 37" src="https://user-images.githubusercontent.com/22769111/28564547-98d179d4-7129-11e7-9955-f4ee22422ace.png">

**Comment by fuzzylogic2000** [comment]
Fixed in #237
