### ISSUE TITLE
shadow on idea tiles

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#213]
the 1px shadow / bottom line on idea tiles is missing. 
It's supposed to be the same we have on blog post teasers. 

<img width="496" alt="bildschirmfoto 2017-07-25 um 10 21 55" src="https://user-images.githubusercontent.com/22769111/28564628-e0922d86-7129-11e7-8874-c3980c48e323.png">

**Comment by fuzzylogic2000** [comment]
Fixed in #237
