### ISSUE TITLE
mobile: blog head dimensions

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#216]
This head section should have the same height like in the idea space. 

Also, it would be awesome if the category filters could align horizontally instead of vertically on mobile – if that's feasible

<img width="781" alt="bildschirmfoto 2017-07-25 um 11 16 31" src="https://user-images.githubusercontent.com/22769111/28564875-b8cb007e-712a-11e7-9123-b208eda3e972.png">

**Comment by fuzzylogic2000** [comment]
This was partly fixed in #237 ?

**Comment by fuzzylogic2000** [comment]
So, just to make sure: the height of the head section of the blog/stories-thing should have the same height as the header of the idea space? But only, if there is no featured blog entry?!

**Comment by fuzzylogic2000** [comment]
@damusp The blog has a featured blog entry on the first site of the pagination. Should I only make the head section smaller if that's not there? Or may I just move it below the categories on mobile (and by that make it less featured on mobile- it will still be the first entry, but not visually distinguashable from all other entries).

![bildschirmfoto vom 2017-08-10 09-06-33](https://user-images.githubusercontent.com/8178179/29158426-3da3b674-7dab-11e7-8f6a-eeedd7149f2d.png)

**Comment by damusp** [comment]
Ah, I forgot about the featured entry! Sorry

Seeing this now I feel like what is actually bothering here is the top-padding for the titles "blog" and "all ideas". So the blue background can have different heights but the placement of the title should be the same.

**Comment by fuzzylogic2000** [comment]
Ok, so the title for the ideaspace should also have the same top offset as the title of the blog?! I'd say, we should wait if the ideaspace gets a subtitle before we change anything there.

**Comment by damusp** [comment]
Okidoki!

**Comment by fuzzylogic2000** [comment]
@damusp 
![bildschirmfoto vom 2017-09-04 09-30-39](https://user-images.githubusercontent.com/8178179/30016154-35d90f22-9154-11e7-8984-a92b6329e638.png)
Ok, with the subtitle, the title for the ideaspace is quite high up. And putting the title for the blog page to the same height looks rather strange, when there is no featured blog entry. Should we leave the old heights? And do we need to change the padding in the ideaspace? (Would be good to know how long the subtitles are meant to be.)

**Comment by damusp** [comment]
Hoy,
I propose that we always hafe the same top offset, but are mostly flexible with the height of this area, like in these examples: https://zpl.io/adxxOlR 






![titles](https://user-images.githubusercontent.com/22769111/30263256-75ce73bc-96d4-11e7-90fc-cc8c360230b3.png)

**Comment by fuzzylogic2000** [comment]
This seems to be solved apart from a new problem: 

![screenshot from 2017-11-22 14-16-47](https://user-images.githubusercontent.com/8178179/33129353-e64d1c44-cf8f-11e7-976e-475ca55d2c3f.png)

Ha, and here:
![screenshot from 2017-11-22 14-18-52](https://user-images.githubusercontent.com/8178179/33129435-2102af34-cf90-11e7-8a14-aabfda06800a.png)

Se we are kind of back to the old problem, but with subtitles.
