### ISSUE TITLE
after creating one proposal you can still reach the create dialog via the url

### ISSUE THREAD

**Issue by slomo** [liqd/a4-advocate-europe#221]

**Comment by fuzzylogic2000** [comment]
@slomo Not really (anymore?). If a paste the create-url of an existing proposal into a new tab, I get a 404.

**Comment by fuzzylogic2000** [comment]
@slomo Hmm, the 404 only appears, after some button is pressed in the create wizard. Otherwise, it won't show the page because of too many redirects.
