### ISSUE TITLE
Display URL as website name not only 'Website'

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#223]
When publishing a website in the account settings it is that 'Website' in the User Profile. Should be the URL instead from my perspective.

![website](https://user-images.githubusercontent.com/15954895/28677325-7ca03758-72ed-11e7-9566-a69b8cd1d08c.png)

**Comment by slomo** [comment]
Not a bug but a feature. Displaying the url might become to long and blow the design. In the weekly we discussed that it could be an improvement to only display the hostname. We will leave that for later and solve it in this sprint.

**Comment by gereonrahnfeld** [comment]
will leave it for now and close it.
