### ISSUE TITLE
Sorting for 'oldest' in User Profile shows weird mistakes

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#224]
User Profile shows me two proposals I support. 
When I sort for 'oldest' in sth weird happens. One of the supported Proposals gets duplicated and is shown instead of the other one. 
Also the number of comments seems to change.

![bildschirmfoto 2017-07-27 um 17 09 12](https://user-images.githubusercontent.com/15954895/28677705-a29a5438-72ee-11e7-90d1-fda5ffd217f9.png)

![bildschirmfoto 2017-07-27 um 17 09 23](https://user-images.githubusercontent.com/15954895/28677710-a5d0c196-72ee-11e7-8a62-84e21219526f.png)

**Comment by MagdaN** [comment]
when ordering for oldest, it actually says 'ordering=comments' in the url see here: https://ae-dev.liqd.net/de/profile/ggr/ (error only occurs when filtering for supported as well)
