### ISSUE TITLE
Following Twitter link doesn't work

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#226]
When I want to follow a twitter link in a User Profile it shows me:
(Same goes for instagram and facebook)

![bildschirmfoto 2017-07-27 um 17 21 09](https://user-images.githubusercontent.com/15954895/28678221-178b92d8-72f0-11e7-95c8-3b979f45709c.png)

**Comment by MagdaN** [comment]
This is not wrong in code, but somehow the current master is not deployed (see https://travis-ci.org/liqd/a4-advocate-europe/builds/259382308) 

@slomo could you take a look what is causing the error

**Comment by MagdaN** [comment]
This is not wrong in code. I think the deployment is broken (see https://travis-ci.org/liqd/a4-advocate-europe/builds/259382308)

@slomo can you check whats wrong here

**Comment by slomo** [comment]
It is wrong in code and deployment. I fixed the deployment the code fix is in #232
