### ISSUE TITLE
wrong collaborator is displayed after a collaborator was added

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#268]
Having logged in with ggr as administrator I added ggr+9 as a collaborator to the proposal 'Deserunt adipisci vitae enim'. When I went to the idea view a new collaborator was shown but it was ggr and not ggr+9.

![ggr 9](https://user-images.githubusercontent.com/15954895/29317403-1737e22e-81cc-11e7-9ef5-7b99f0e360a7.png)

![ggr](https://user-images.githubusercontent.com/15954895/29317402-121be358-81cc-11e7-9e3c-5fac6488debb.png)

**Comment by gereonrahnfeld** [comment]
I have the feeling that whenever I want to add a new collaborator, not the collaborator is displayed but the user who invited the collaborater (myself). 

![bildschirmfoto 2017-08-16 um 16 29 17](https://user-images.githubusercontent.com/15954895/29368724-dc341064-82a0-11e7-83b6-fd4dc6a72906.png)

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld That was solved by logging out before accepting the invitation, right? I will close the issue. Please reopen if still an issue.
