### ISSUE TITLE
Should we move jury_statement from proposal to idea

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#278]
At the moment jury_statement is a field in proposal but is_winner is a field in idea. I think both fields should belong to one model either idea or proposal - i would suggest to move to idea as otherwise we have to adapt the filters again.

@slomo @fuzzylogic2000 what do you think?

**Comment by fuzzylogic2000** [comment]
@MagdaN Good point! Please!

**Comment by fuzzylogic2000** [comment]
That already happened by now!
