### ISSUE TITLE
After adding proposal, idea sketch is not displayed anymore

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#282]
After I have extended my idea sketch to a proposal I have the possibility to switch between the proposal and idea. However, when I first go to proposal and then want to switch back to idea it doesn't show me any information anymore, except the collaborators (who are displayed on the wrong side).

![bildschirmfoto 2017-08-16 um 16 09 37](https://user-images.githubusercontent.com/15954895/29367586-ad6b471e-829d-11e7-9557-d7e579e465bd.png)

**Comment by fuzzylogic2000** [comment]
Kkrrrrk, because the idea is a winner and there are journey entries, the wrong (non-existing) journey-tab is active.

**Comment by MagdaN** [comment]
This is not fixed: go to https://ae-dev.liqd.net/de/ideas/deserunt-adipisci-vitae-enim/ ...
