### ISSUE TITLE
Displaying category 'community' in stories section is broken

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#297]
When choosing the category 'community' in the stories section on ae-stage the following view is broken. 

![bildschirmfoto 2017-08-21 um 14 01 23](https://user-images.githubusercontent.com/15954895/29518492-dd5af8fe-8679-11e7-8b9e-e09e87db6824.png)

**Comment by fuzzylogic2000** [comment]
Related to #203. Happens, because the categories don't currently have a height.

**Comment by gereonrahnfeld** [comment]
Alright, I'll close the issue then.
