### ISSUE TITLE
Issues with imports

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#302]
- activities show date of import
- comments have latest edit set to import date
- 2016: on old advocate europe page there are 637 proposals, imported are 448 ( three winners are missing)
- 2015: on old advocate europe page there are 581 proposals, imported are 576
- fallback image for ideas: https://ae-dev.liqd.net/de/ideas/proposal_0000635/
- 2015 and 2016: community award winner doesn't have the community award badge

**Comment by slomo** [comment]
Integrated into #233 The small differences are due to projects that don't validate. The bigger differences in 2016 have been solved.
