### ISSUE TITLE
Ideaspace should display number of proposals for filter

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#304]

**Comment by fuzzylogic2000** [comment]
@damusp we also need a design for that

**Comment by damusp** [comment]
Do you think a simple solution like this would do it – showing the amount in brackets? 

![ideaspace_01](https://user-images.githubusercontent.com/22769111/30316823-b42ff9c6-97a8-11e7-91ab-a04f8fe79c9b.png)

**Comment by MagdaN** [comment]
I would rather display the number of items after the filters have been applied, as with this solution it is not clear if applied filters are taken into account or not. Also, this solution is rather hard to implement.

**Comment by damusp** [comment]
I follow you. In this case we could just show the amount of results next to the pagination. 

![ideaspace_02](https://user-images.githubusercontent.com/22769111/30324610-f08677ec-97c1-11e7-8196-dda0f4a5a58c.png)

Does this make sense to you?

**Comment by MagdaN** [comment]
Looks good
