### ISSUE TITLE
+add proposal is shown too many times

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#306]
Have you seen that when clicking on the arrow on the rights side of the user name the "+add proposal" button is shown three times? Perhaps there is a connection to the migrations?

![bildschirmfoto 2017-08-22 um 15 45 20](https://user-images.githubusercontent.com/15954895/29568607-1fc62aa6-8751-11e7-819c-b4514cb27355.png)

**Comment by MagdaN** [comment]
this is because you are logged in as administrator - you can add proposals to 2015, 2016 and 2017. But I those links are going to be removed anyway (???)

**Comment by gereonrahnfeld** [comment]
should work as it is. will close for now
