### ISSUE TITLE
Configure i18n support according to requirements

### ISSUE THREAD

**Issue by slomo** [liqd/a4-advocate-europe#310]
**Requirements:**

- cms content should be in English and German
  - except for Blog
  - a link to switch languages should be offered
- idea space (and wizards, detailed idea sketch, project journey etc) should only be in English
- User Profile (dashboard) and Account Settings should only be in English
- main menu and footer should always be in user language
   - a link to switch languages should be present on all sites

**Todo:**

- [x] Ignore issue with Blog, because that is not supported by wagtail?
- [ ] force content of idea space to English (WIP: #353)

**Related issue**:

- ~~#308: still relevant~~
- #116: will be fixed afterwards (WIP: #353)

**Comment by slomo** [comment]
@gereonrahnfeld @rukala Could you check that the requirements are right?

**Comment by MagdaN** [comment]
what about the register and login pages? They can be translateable.

**Comment by gereonrahnfeld** [comment]
Finally I received the info concerning the translations from Christina. 
The following pages should only contain content in English:
- idea space (including form/ wizard and detailed idea sketch/propsal/project journey)
- User Profile (dashboard) and account settings

Everything else should be translatable in English and German (e.g. landing page, CMS content ..)

I updated the requirements accordingly.

**Comment by slomo** [comment]
I added the requirement that the main menu should always be in user language and therefore the language switch should always be present.

**Comment by slomo** [comment]
Has the fix from #353 also be adapted for the user profile and account settings. I guess the blog we choose to ignore as of right now?
