### ISSUE TITLE
Provide proper fallback image for ideas

### ISSUE THREAD

**Issue by slomo** [liqd/a4-advocate-europe#318]

**Comment by fuzzylogic2000** [comment]
And the blog tiles!

**Comment by damusp** [comment]
How about a pattern – it can easily be used at every size. 

<img width="632" alt="bildschirmfoto 2017-09-14 um 12 02 26" src="https://user-images.githubusercontent.com/22769111/30423946-b447e75a-9944-11e7-8b2e-f479f0f7c125.png">

(Can be seen on dev)

**Comment by fuzzylogic2000** [comment]
Uh, I like it!

**Comment by damusp** [comment]
For ideas the yellow one works better, because in the detail view it stands out better against the background. 

Here are the images:
![pattern_triangles_02](https://user-images.githubusercontent.com/22769111/30426253-a35f86ee-994b-11e7-8402-9ff09924573f.png)
![pattern_triangles_01](https://user-images.githubusercontent.com/22769111/30426254-a3616eaa-994b-11e7-8246-1ada3ec8aa38.png)

**Comment by slomo** [comment]
But won't we have an issues with visibility of badges on the yellow one?

**Comment by damusp** [comment]
Ah, yes! 

In the design there's a subtle gradient on idea tiles, this helps the badge to stand out. 
![bildschirmfoto 2017-09-18 um 09 42 56](https://user-images.githubusercontent.com/22769111/30533260-b3891156-9c58-11e7-9c47-aa92a890cc8f.png)

**Comment by mkind** [comment]
@slomo the tile pattern could also be implemented using `background-repeat`. If so, we can reduce image size and do not need multiple placeholders for different resolutions. what do you say?

**Comment by damusp** [comment]
Here's a compressed svg file: 


[pattern_triangles_02.svg.zip](https://github.com/liqd/a4-advocate-europe/files/1313850/pattern_triangles_02.svg.zip)

**Comment by mkind** [comment]
> Here's a compressed svg file:

Would you mind, attaching the blue one too.

**Comment by damusp** [comment]
Ah yes, here's the blue one. 

[pattern_triangles_01.svg.zip](https://github.com/liqd/a4-advocate-europe/files/1317251/pattern_triangles_01.svg.zip)
