### ISSUE TITLE
Community award information gets lost

### ISSUE THREAD

**Issue by slomo** [liqd/a4-advocate-europe#319]
Currently if a project is winner, it is not visible anymore whether it has won a a community award. If we don't show the information in the tile we could at least show it on the detail page.

**Comment by MagdaN** [comment]
That is a requirement by customer

**Comment by slomo** [comment]
I understood the following requirements:
  - each project tile should exactly show one badge
  - the most important badge should always be show
     - winner (most important)
     - community award
     - shortlist (least important)
  - no requirements for the detail page header
 
This is a bit conflicting with a subissue from #233 where it describes the current behaviour as a problem.

@gereonrahnfeld Could you clarify here, which of the two conflicting requirements is right?

**Comment by slomo** [comment]
It has been clarified that there should always be only one badge.
