### ISSUE TITLE
The tabs Login and Register should be centred 

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#324]
The tabs register and login in the new login/ register dialogue should be centred. At the moment they are a bit too far left. And the colours should change. According to the designs the color of the tab that is selected should be blue and the un-selected black. At the moment it is the other way round. 

![bildschirmfoto 2017-08-28 um 14 18 18](https://user-images.githubusercontent.com/15954895/29773090-20410a28-8bfc-11e7-9a5a-f3ac9ee7691c.png)

**Comment by MagdaN** [comment]
In the designs the tabs are not centered, I was also wondering about that. For the colours, I think it feels a bit odd to change this: blue is the link color, so that would mean the blue is the color for links but just here it is the other way around. What do you think?

**Comment by fuzzylogic2000** [comment]
I also think it's a bit odd, to use the blue for "selected", but it is the same way around on the idea detail (for the tab and the proposal/idea-sketch links). I'd say we should use it the same way everywhere.

**Comment by gereonrahnfeld** [comment]
yes, I agree. I think the most important is to be consistent on the platform. I'll speak to David about changing this when he comes back.
