### ISSUE TITLE
active link in ae-primary are confusing

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#333]
@damusp Active links are blue, so that they look clickable while the actual links are black. Even though I like the design, it clashes with what the users are used to. I think it is ok for the tabs on the idea detail, the user profile, and the login, but for the proposal/idea sketch links it might make sense to change it. And/or we should check that all links (also to the collaborator's profiles) look the same and are not blue.

@gereonrahnfeld @MagdaN somewhere else, where we should check how we use the brand-primary for text?

**Comment by damusp** [comment]
I personally think it is totally fine. Same as the tabs, active is highlighted. I think for all other cases, links should be blue as they currently are. 

Here's the case that you mentioned:

<img width="676" alt="bildschirmfoto 2017-09-11 um 13 38 56" src="https://user-images.githubusercontent.com/22769111/30272823-9772f174-96f6-11e7-887a-8880a9a44551.png">

Something else is bothering me: the active one should not be clickable, as it is already selected. I think this would make it a little less confusing. Would you be satisfied, or still unhappy @fuzzylogic2000?

**Comment by fuzzylogic2000** [comment]
I am happy anyway, but found it confusing, that the links to the collaborators profile on the same page were blue. Checking zeplin, I saw they should be black.
So: 

- [ ] Make the selected idea sketch/proposal link unclickable
- [ ] Style the collaborator links according to design
