### ISSUE TITLE
subtitle in idea space goes too far to the margins and overlaps with filters on smaller screens

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#358]
When creating a longer subtitle witin the idea space it goes quite far to the margins (image 1). Perhpas it would be nice to have it only within the container? When it comes to smaller screens it overlaps with the filters (image 2). Also the title is affected (image 3).
@damusp : could you please have a look and find a nice solution and speak with the devs about it? cheers.

![bildschirmfoto 2017-09-04 um 18 03 35](https://user-images.githubusercontent.com/15954895/30033577-50658210-919c-11e7-96bd-048d8dc14da6.png)

---------

![bildschirmfoto 2017-09-04 um 18 04 54](https://user-images.githubusercontent.com/15954895/30033580-53b01a20-919c-11e7-91ce-d71fcdaccd6b.png)

---------

![bildschirmfoto 2017-09-04 um 18 05 59](https://user-images.githubusercontent.com/15954895/30033581-56837490-919c-11e7-8bba-7110f475d6ca.png)

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld after merging #365 will use the name as subtitle, so that it can't get as long
@damusp you should probably still take a quick look at it.

**Comment by gereonrahnfeld** [comment]
will close for now and tell David to have a look at subtitle when he is back.
