### ISSUE TITLE
Add 'All' to Participation Filter in User Profile

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#359]
In the User Profile I can filter the proposal I participate in by submitted, supported and watching. Additionally I would like to have the possibility to view all the proposals I participate in at the same time. All should be the default filter. 

![bildschirmfoto 2017-09-05 um 10 36 18](https://user-images.githubusercontent.com/15954895/30052676-88170122-9226-11e7-8235-cf1ee22a4baa.png)

**Comment by slomo** [comment]
I think this is different from what @damusp designed. And one reason here is, that it doesn't make sense to mix ideas in which in contributed and watched in the same list without an option to tell them apart.

**Comment by gereonrahnfeld** [comment]
ok, I got the argument. Will close the issue for now.
