### ISSUE TITLE
When I watch a new proposal this is not listed in my activity stream

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#361]
Even though it wasn't part of the requirements I think it would be nice to see in the activity stream if a User watches a new proposal. 

![bildschirmfoto 2017-09-05 um 10 37 28](https://user-images.githubusercontent.com/15954895/30052876-47e89e16-9227-11e7-8124-7b6d2569c839.png)

**Comment by fuzzylogic2000** [comment]
fixed with #369
