### ISSUE TITLE
Project journey: provide context when adding entries

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-advocate-europe#370]
Currently when adding a new entry to a project log, the user is taken to new page that offers no context on which project the user writes an entry for. It would be great to provide the title of the idea (project) somewhere (maybe in smaller type above the headline „Create new entry“).

Also, this form needs a cancel button, which brings you back to the reporting tab of the project.

I can’t provide screenshots at the moment, as I don’t have the admin rights on ae-dev. (Already asked Katharina about it). 

Was discussed with @gereonrahnfeld

**Comment by MagdaN** [comment]
![bildschirmfoto 2017-09-21 um 14 15 26](https://user-images.githubusercontent.com/2905743/30695143-5737ba7a-9ed7-11e7-8839-3110cc22c419.png)

@damusp can you add a design or tell me how this is supposed to look

**Comment by damusp** [comment]
we might add the project title and a "back to idea"-button 
![journeyentry_01](https://user-images.githubusercontent.com/22769111/30849391-7f4b8298-a2a2-11e7-84e2-bc9a5e81c018.png)




Or go even further and show the project context by using …modals! 
![journeyentry_02](https://user-images.githubusercontent.com/22769111/30849393-8174ced0-a2a2-11e7-9f01-6a88257adc2a.png)

**Comment by gereonrahnfeld** [comment]
I like the second version. Would that be possible @MagdaN ?

**Comment by MagdaN** [comment]
Yes, it is possible, but is way more work then version one.

**Comment by fuzzylogic2000** [comment]
I do not think, the few people that will ever see and use it, justify the work, so I would prefer version one.

**Comment by gereonrahnfeld** [comment]
I agree.

**Comment by damusp** [comment]
yeah, it's the wiser thing to do 👌
