### ISSUE TITLE
The button "All ideas" takes me to the filtered idea list

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#378]
I find it confusing and annoying, when I am in the idea detail view and instead of clicking the browsers back-button use our "All ideas"-button, which takes me to the filtered (with the default filters from the phases) idea list view.

**Comment by damusp** [comment]
Could this be solved by not applying any filters in that particular case? 

Or should we change the naming for the "All ideas"-button? (e.g. "Back to Idea Space")

**Comment by MagdaN** [comment]
I think simply changing the name to 'All ideas' should fix the problem. What do you think?

**Comment by fuzzylogic2000** [comment]
Yes, changing the naming would be good! 

Maybe just "Idea Space" or "< Idea Space"? I think "Back to..." would still be confusing, because the filters that were selected before are gone.

**Comment by damusp** [comment]
Yeah, I am all for "< Idea Space"!
