### ISSUE TITLE
delete all real imported ideas from ae-dev

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#384]
If we test stuff with the real ideas, people might get emails. Should we delete all the old ideas to make sure, this doesn't happen?

**Comment by MagdaN** [comment]
other idea: change email address for all ideas creators

**Comment by gereonrahnfeld** [comment]
other idea: only test with 2017/18 ideas?!
is this issue still relevant @fuzzylogic2000 @MagdaN ?

**Comment by MagdaN** [comment]
I think this can be closed

**Comment by gereonrahnfeld** [comment]
alright, I will close. If still important please re-open.
