### ISSUE TITLE
tile images are stretched on mobile in carousel

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#388]

**Comment by fuzzylogic2000** [comment]
![bildschirmfoto vom 2017-09-12 09-12-15](https://user-images.githubusercontent.com/8178179/30312608-85f7a580-979a-11e7-8504-616d3542666c.png)

@gereonrahnfeld To fix this, we have to take back the fix to #362 But this only happens, when an image that was selected and still has the link in the database, is deleted from the repective folder. This shouldn't happen and if it does, we can also delete the link from the database.

**Comment by fuzzylogic2000** [comment]
Ok, the slider introduces an inline style overwriting our tile-width. So,we could also make that width important and keep both problems fixed. But this breaks the carousel. The tiles in the middle are not always greyed out anymore. And as this is only a problem in the slider, which should always be filled with "good" ideas, that should have images, I'd say, we fix it there as proposed by not setting a height for the image.
