### ISSUE TITLE
Support button // Heart styling and animation

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#401]
Currently, the "support"-heart looks like this:
<img width="227" alt="bildschirmfoto 2017-09-13 um 10 42 47" src="https://user-images.githubusercontent.com/22769111/30368707-4d9872cc-9872-11e7-9ea8-b3738b412090.png">

Here's what I had in mind – stacked icons:
![bildschirmfoto 2017-09-13 um 10 57 38](https://user-images.githubusercontent.com/22769111/30368748-78c3c212-9872-11e7-8f91-ad14db2206bc.png)

**Comment by damusp** [comment]
But maybe we could go even further, with animations! I think this could make the act of supporting much more delightful, even if it's just a detail. Here's an example from twitter: 
https://codepen.io/mindstorm/pen/aZZvKq

Do you think we could create a similar effect for AE?

**Comment by mkind** [comment]
@damusp If we want to implement this, we need a proper image like in [your example](https://cssanimation.rocks/images/posts/steps/heart.png).

**Comment by damusp** [comment]
Here's a spritesheet we could use for a first iteration. 
It has got 19 frames instead of 29. 

![testsprite_01](https://user-images.githubusercontent.com/22769111/30594551-bbc48b74-9d4e-11e7-9187-540fc37e3e37.png)


It would look kinda like [this](http://is.si/animator/?sW=100&sH=100&fC=43&fT=40&c=00AAE6&b=0&img=https%3A%2F%2Fae-dev.liqd.net%2Fmedia%2Fimages%2Fsprite01.original.png)
