### ISSUE TITLE
button behaviour

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#405]
### hovering over a button 
- triggers hover style (darker color)
- cannot be clicked

### hovering over a button label 
- triggers another hover style (underline)
- can be clicked 

This is a problem – there should be no underline here, and all of the button should be clickable!

**Comment by damusp** [comment]
this actually only happens with the "all ideas"-button, i think

**Comment by fuzzylogic2000** [comment]
Well, I found more. There are some on the landing page as well. And I guess on the blog detail page. But I am curreńtly fixing all of these!
