### ISSUE TITLE
Hover style for tiles

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#409]
We have different kinds of tiles:
- Idea tiles
- Blog tiles in various sizes

But we do not yet have a consistent hover style! Here's my proposal:
- no underline 
- headline gets #gray-middle
- zooming background-images https://css-tricks.com/zooming-background-images/

**Comment by MagdaN** [comment]
I like it! We should implement it

**Comment by fuzzylogic2000** [comment]
I am sorry, we can't implement that. Otherwise I can't take part in the next sprint, because I'll have to hover tiles all day. Ehm no, real question:
Should the whole tile link to the idea (or blog post) or are title and image sufficient?

**Comment by damusp** [comment]
oops, sorry, I've overlooked your last message. 
title and image are sufficient!
