### ISSUE TITLE
Idea Space: padding when there is no pagination 

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#426]
When there is no pagination, the space between the ideas and the footer should be 60px. 

<img width="1280" alt="bildschirmfoto 2017-09-15 um 13 07 22" src="https://user-images.githubusercontent.com/22769111/30479763-fe5faee0-9a16-11e7-959b-f3a744cb154d.png">

**Comment by fuzzylogic2000** [comment]
Should be fixed with the included idea-count.
