### ISSUE TITLE
user indicator dropdown scrolling on mobile

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#440]
If the user indicator opens, one needs scrolling to use the menu. As the menu is very tiny and mobile users need to use big fingers, it might be an issue.

![30533042-a9780ea2-9c57-11e7-90d9-f76815a58e74](https://user-images.githubusercontent.com/8178179/30633748-1a0ea28e-9ded-11e7-9897-44ab8702bbc1.png)

**Comment by fuzzylogic2000** [comment]
I think that's only an issue for admins with small phones, so we probably do not need to fix it.

**Comment by gereonrahnfeld** [comment]
will close for the time being and re-open if necessary
