### ISSUE TITLE
new fallback image does not work with facebook

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#454]
If we want to use the fallback image also as fallback image for the social media sharing stuff, we need to provide it as png instead of svg (at least for facebook/the og format).

It might be a good idea to use an extra fallback image (like our fallback with the logo or something like this) anyway?

**Comment by gereonrahnfeld** [comment]
A fallback image with the AE logo is a good idea I think- otherwise it might be difficult to grasp the context immediately.

**Comment by damusp** [comment]
Having the logo show up on social media posts is a good idea in my opinion. Not just as a fallback, but for all Advocate Europe posts. 

On the platform though the pattern makes for a much nicer fallback image.

**Comment by fuzzylogic2000** [comment]
Ok, so I use the logo for all posts about ideas and new blog entries? Never the images from the ideas or blog posts? (Currently for the blog the logo is only used when the image is not given, so in the fallback case.)

**Comment by damusp** [comment]
Yes, I would say this would be a good idea. 

@gereonrahnfeld, what do you think?

**Comment by gereonrahnfeld** [comment]
Why not - I trust you David. Can't decide what I would prefer.
