### ISSUE TITLE
Call to action // text positioning

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#461]
The call-to-action-tile should have the same spacing as the idea tiles, like so: 

![call to action](https://user-images.githubusercontent.com/22769111/30846953-f1b37998-a299-11e7-9b8b-b526b2c5bb36.png)

**Comment by fuzzylogic2000** [comment]
@damusp To get that working with flexbox, we'll need the logo in an image with the aspect ratio 2:1 and the right padding. Meaning everything above the first red line as an image with a transparent background.

**Comment by damusp** [comment]
this would be one with 600x300px:

![logo](https://user-images.githubusercontent.com/22769111/30850697-a0b1c40c-a2a6-11e7-9263-dca6e8fad641.png)

**Comment by fuzzylogic2000** [comment]
Awesome! Thanks!
