### ISSUE TITLE
Design needed

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#470]
How should the idea space look, when I can participate and the cta-tile is shown but no other ideas are there. At the moment at would look like that:
![bildschirmfoto 2017-09-27 um 16 55 38](https://user-images.githubusercontent.com/2905743/30920680-e284e694-a3a4-11e7-9e9c-5b37c76a0502.png)

@damusp anny idea?

**Comment by damusp** [comment]
hows about something like this: 




<img width="689" alt="bildschirmfoto 2017-09-27 um 17 15 09" src="https://user-images.githubusercontent.com/22769111/30921765-9020ca0a-a3a7-11e7-9fe0-b70a2412ccaf.png">

**Comment by MagdaN** [comment]
cool

**Comment by fuzzylogic2000** [comment]
MagdaN already implemented that!
