### ISSUE TITLE
Account Settings: Social Connections are messy

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#472]
Some text elements here are confusing, especially the "**or** use your social media account". 
<img width="881" alt="bildschirmfoto 2017-09-27 um 15 49 15" src="https://user-images.githubusercontent.com/22769111/30955179-094dd428-a433-11e7-80b6-811375364fda.png">

I would say we should leave some of it away and it already becomes much simpler to understand: 
![accountsettings_connections](https://user-images.githubusercontent.com/22769111/30955180-0951266e-a433-11e7-8b93-fb24dc7d1db3.png)

**Comment by fuzzylogic2000** [comment]
Already solved!
