### ISSUE TITLE
Blue box of idea space is too big

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#481]
I think it is a nice solution that you came up with for integrating the new filter UI - however the blue box is too big I think. Could we find a solution where the hight of the lower edge in relation to the ideaspace is similar to for example the hight of the lower edge of the blue box in the blog section in relation to the blog entries?

![bildschirmfoto 2017-10-02 um 11 50 56](https://user-images.githubusercontent.com/15954895/31072918-2e3a9250-a76a-11e7-84cf-1017e3dd4ab9.png)

**Comment by slomo** [comment]
There is also the password reset view, email activation view, idea detail which all have also a blue background, should those be changed as well?

**Comment by slomo** [comment]
Fixed for idea space.
