### ISSUE TITLE
Tile in idea space too big

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#482]
![bildschirmfoto 2017-10-02 um 12 08 29](https://user-images.githubusercontent.com/15954895/31073007-7801d042-a76a-11e7-8d0e-668b9814b76a.png)

**Comment by slomo** [comment]
The tiles are responsive, which mean the grow to fit their content. In the case of text this means the tile is as wide as the the longest word in its test. In the particular example `INEQUALITY(Indiviual,Cultural,Stuctural).We` Is written without spaces and therefore considered a word.

In short I don't know what would be a better solution here. Should we let the text overflow to outside of the tile? Or should we simply hide that overflow. Should all tiles increase in width to accommodate the largest tile (not sure if that is even possible).

**Comment by gereonrahnfeld** [comment]
@slomo  thanks for explaining what is happening here. 

The tiles should not increase in size I think. They would become too big. 
The text should also not overflow to outside the tile - would look very weird. 
The text could overflow to the outside and the overlow is then hidden - even though this is not the perfect option either. 
Could we, perhaps, force a word to be cut in two pieces (adding a '-') when the word is too long for our tiles?

**Comment by slomo** [comment]
I cont choose the symbol, but I can instruct the algorithm to split between any characters, and smart one in browser will hopefully then select good locations for wrapping.
