### ISSUE TITLE
latest blog entries have different sizes when using safari

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#487]
![bildschirmfoto 2017-10-02 um 12 47 50](https://user-images.githubusercontent.com/15954895/31074257-0a243906-a770-11e7-80d9-0be64eb6ba12.png)

**Comment by fuzzylogic2000** [comment]
Umph, I don't know the best/sensible/any good way to fix it. Min-height with media-queries?
