### ISSUE TITLE
notification for new journey entry doesn't work

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#489]
I neither receive a notification as a collaborator when the creator issued a new journey entry,
nor do I receive a notification as a creator when a collaborator issued a new journey entry.

**Comment by mkind** [comment]
Well, isn't that implemented in the unmerged PR https://github.com/liqd/a4-advocate-europe/pull/468. @fuzzylogic2000 is working on that.

**Comment by gereonrahnfeld** [comment]
alright. didn't know about it - our analogue taskboard suggested that I should start testing.

**Comment by mkind** [comment]
![](https://static.squarespace.com/static/518f5d62e4b075248d6a3f90/t/529265dee4b03e7a0729af8a/1385326056122/git-blame2.jpghttps://static.squarespace.com/static/518f5d62e4b075248d6a3f90/t/529265dee4b03e7a0729af8a/1385326056122/git-blame2.jpg)
