### ISSUE TITLE
Improve wizard navigation

### ISSUE THREAD

**Issue by slomo** [liqd/a4-advocate-europe#49]
Currently the wizard only allows to jump back to any previous step (through the progress list) or go back to the last step (using the back button). In the first case the data is stored, but therefore required to be valid. While in the latter case everything entered in the current form is lost.

The whole behaviour should be more consistent. The ideal solution would be:

 - you can go to any previous step (by clicking on the progress bar or the back button)
 - if you go back data will be stored but not validated (yet)
 - you can jump forward (using progress bar)
    - if the current step is valid
    - if the target step is right after the latest validated step

This tries to make sure that all forms are valid, that are before the currently active form, while keeping it as flexible as possible. It requires us to ensure that each step can be validated on its own and we can not use the conditional step feature of the wizard (both requirements are full filled currently).

An easier solution would be, to require a form always to be valid before leaving it.

**Comment by slomo** [comment]
@damusp I would be interested in your opinion on the matter.

**Comment by damusp** [comment]
Hoy @slomo, the solution you proposed seems very smart to me. 
It would work both for creating and editing ideas, in a user-friendly and understandable way. Personally I can't see any downside to it. 

![slice](https://cloud.githubusercontent.com/assets/22769111/25801830/be463e06-33ef-11e7-8014-ed57a4a04943.png)

**Comment by fuzzylogic2000** [comment]
When I create an idea sketch, in the last step I can't use the progress bar to go back to an earlier step. Instead the idea sketch is stored. The back-button works, though. If I am in an earlier step the navigation works.
As the collaborator notifications are send in the last step, this also shouldn't happen, when I do not send the idea sketch. Might be tricky, when all other validations are to take place before navigating?
