### ISSUE TITLE
Account settings: two bios are too much!

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#498]
<img width="580" alt="bildschirmfoto 2017-10-05 um 11 54 02" src="https://user-images.githubusercontent.com/22769111/31224555-b8b5fdfa-a9ce-11e7-834c-bba7b93c830b.png">

Instead of two fields there should only be one, but one that's more open to the user's personal preferences. 
The label could say something like: 

**Tell us about you**
_For example your background, your interests, your motivation for change in Europe (144 chars)_

**Comment by damusp** [comment]
@gereonrahnfeld has given his approval for this

**Comment by gereonrahnfeld** [comment]
we still have to doublecheck with MitOst - happens as soon as they send us their input for the Account Settings

**Comment by fuzzylogic2000** [comment]
done!
