### ISSUE TITLE
Watch dropdown Styling

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#500]
**1) Hover style doesn't work correctly.** 
When I hover inside the dropdown, the "watch" button gets affected instead (already works with the "Share" dropdown!)

**2) The options are sticking too close together.** 
Adding 10px of space before, between and after will help!

**3) would look nicer if the icon was coloured!**
go green! 

<img width="247" alt="bildschirmfoto 2017-10-05 um 13 33 30" src="https://user-images.githubusercontent.com/22769111/31225784-ef1aa38c-a9d3-11e7-80e5-a81f45c14d70.png">

**Comment by damusp** [comment]
**Another thing:** 

The button says "Watch" and "Unwatch", but the options say "Watching" and "Not watching"
Wouldn't it make more sense if these matched instead of saying similar yet different things? 

–> my suggestion would be to change the buttons labels into "Not watching" and "Watching", so they reflect the current state.

**Comment by fuzzylogic2000** [comment]
Yes, I will do the styling. 
@gereonrahnfeld But should we really change the wording and if yes, how? The current version is like the wording on github (scroll up). On the button it says the action, you can do when clicking the button, while in the dropdown it tells you what you currently do. I think if you're watchíng and the button also says "Watching" it is not that clear, what you can actually do when clicking the button? And even worse, when you're on that page for the first time and it says "Not watching" with the crossed out eye it seems strange to me, not very CTA.

**Comment by gereonrahnfeld** [comment]
@fuzzylogic2000 I think you are right. The wording for the button should be activating while the wording in the dropdown has a rather descriptive purpose. And I think this dual mode is not irritating at all but quite self-explaining. Therefore I would suggest to keep the wording like it is.

Thus, I think we should only change the following comments from David:

1) Hover style doesn't work correctly.
When I hover inside the dropdown, the "watch" button gets affected instead (already works with the "Share" dropdown!)

2) The options are sticking too close together.
Adding 10px of space before, between and after will help!
