### ISSUE TITLE
Landing page: Sections need LESS spacing! 😳

### ISSUE THREAD

**Issue by damusp** [liqd/a4-advocate-europe#503]
Looks like the spacing here is about 60px or something. 

It should be just 20px. 

<img width="514" alt="bildschirmfoto 2017-10-05 um 15 32 02" src="https://user-images.githubusercontent.com/22769111/31229922-939979de-a9e2-11e7-8fad-d563f9d25bec.png">

**Comment by fuzzylogic2000** [comment]
@damusp Between most blocks on the landing page there should be a spacing of 30px (according to your designs). Can I use the same spacing for the tops of the carousel and the story-block, please? Or, otherwise, to which blocks does the extra spacing belong?

**Comment by damusp** [comment]
Hm, how about the tops get 20px and the bottoms get 30px?

**Comment by fuzzylogic2000** [comment]
But then it's 50px between all the elements?! Or do you mean always 20px between the elements, but 30 between the last element and the footer?

**Comment by damusp** [comment]
Yes, it would be 50 then! 


<img width="369" alt="bildschirmfoto 2017-10-06 um 10 09 29" src="https://user-images.githubusercontent.com/22769111/31269297-204a6d82-aa80-11e7-81ef-7291aa619eaf.png">
