### ISSUE TITLE
styling of yellow tab in confirmation email

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#515]
the styling looks a bit weird - the text is very close to the margins - could this please be adjusted to other yellow tabs? thanksy

![styling welcome email](https://user-images.githubusercontent.com/15954895/31385703-808a63ea-adc4-11e7-9424-ac6463310a03.png)

**Comment by fuzzylogic2000** [comment]
@ggr I couldn't reproduce that, but it might be fixed with #563. Please check again, when merged.

**Comment by fuzzylogic2000** [comment]
@ggr Could you please check again on dev? This issue should be fixed now.

**Comment by gereonrahnfeld** [comment]
Looks wonderful. I will close the issue. Thanks a lot.
