### ISSUE TITLE
Messages are translated

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#530]
![bildschirmfoto 2017-10-11 um 17 24 26](https://user-images.githubusercontent.com/2905743/31450228-2d6eed80-aea9-11e7-9bae-476851d5a0a8.png)

**Comment by fuzzylogic2000** [comment]
Force_translation won't force the messages to be english. I guess, we'll have to live with German messages.

**Comment by gereonrahnfeld** [comment]
If this doesn't work, is it possible to have a different text for the German version?

**Comment by MagdaN** [comment]
When I think about it, I think it makes sense, to keep those messages in the users preferred language, as they can be displayed on any page, an I guess it would feel strange, if the messages are sometimes translated and sometimes not.

**Comment by gereonrahnfeld** [comment]
That's true and the way I'd prefer as well.

**Comment by MagdaN** [comment]
OK, cool, then I will close this issue.
