### ISSUE TITLE
Edit comment doesn't work

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#531]
I just tried to edit several comments of the idea 'Make Berlin greater again!' - but it didn't work. 

![bildschirmfoto 2017-10-12 um 11 02 44](https://user-images.githubusercontent.com/15954895/31488128-1abbd75e-af3d-11e7-8676-72d089563cf6.png)

**Comment by slomo** [comment]
This is a know a4 issue and has already been fixed (https://github.com/liqd/adhocracy4/pull/194). So an a4 update should be enough.
