### ISSUE TITLE
Partner Logos are badly displayed on ipad

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#555]
Corina from MitOst discovered that the partner logos are not displayed correctly when checking the website on an ipad. 

![bildschirmfoto 2017-10-25 um 18 11 36](https://user-images.githubusercontent.com/15954895/32009789-584f0e06-b9b0-11e7-86a9-1252a63bc6b7.png)

**Comment by slomo** [comment]
Already fixed on dev. Waiting for release to production.
