### ISSUE TITLE
I don't get a notification when I watch a proposal and someone comments on it.

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#559]
checked by using the following proposal:

![screen shot 2017-10-30 at 14 21 04](https://user-images.githubusercontent.com/15954895/32172928-9be77ae2-bd7d-11e7-9369-75857239ec50.png)

**Comment by slomo** [comment]
Can't reproduce on ae-dev.

**Comment by gereonrahnfeld** [comment]
I think the problem here was that Moderators didn't receive notifications (a filter for this was active). @slomo : this was fixed right? if not please re-open. I will close the issue.
