### ISSUE TITLE
I don't get a notification when I watch an idea and it is modified into a proposal.

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#561]

**Comment by slomo** [comment]
Can't reproduce, notification works on ae-dev for me. But the text is not very helpful.

**Comment by gereonrahnfeld** [comment]
I think the problem here was that Moderators didn't receive notifications (a filter for this was active). @slomo : this was fixed right? if not please re-open. I will close the issue.
