### ISSUE TITLE
A few changes in the wizard are missing.

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#563]
All the changes which haven't been done yet are marked with a red oval:
(Please have a look at google docs for the right wording)

https://docs.google.com/spreadsheets/d/1-GUndJPqHssLNo6srX6Dde1_yeyqP1qjEMySFs9D1Mk/edit?ts=597628f1#gid=71366461

![screen shot 2017-10-30 at 15 12 11](https://user-images.githubusercontent.com/15954895/32175962-ae6d2b4a-bd86-11e7-98be-68b3724be34f.png)

![screen shot 2017-10-30 at 15 14 10](https://user-images.githubusercontent.com/15954895/32175965-b091dbf0-bd86-11e7-9cd5-f69b644e8471.png)

![screen shot 2017-10-30 at 15 16 59](https://user-images.githubusercontent.com/15954895/32175976-b332a8a8-bd86-11e7-8389-3c43e6f43995.png)

![screen shot 2017-10-30 at 15 18 20](https://user-images.githubusercontent.com/15954895/32175981-b4fc0904-bd86-11e7-8e4d-b84285e4a2a8.png)

![screen shot 2017-10-30 at 15 21 10](https://user-images.githubusercontent.com/15954895/32175985-b7323338-bd86-11e7-91de-b65dc5b8a5ae.png)

![screen shot 2017-10-30 at 15 24 41](https://user-images.githubusercontent.com/15954895/32175988-b931dfc6-bd86-11e7-82ec-916212ba3689.png)

**Comment by slomo** [comment]
The current situation for me is: I don't have access to the document linked above. There is the older document, in which there are still some fields marked red. Those fields are known to be different in the current implementation. Some of the fields you have marked here, are those marked fields. Others are exactly implemented as specified in the document, but still reported in this issue. The whole document is marked as not being not final.

In my opinion the fastest way to a solution would be, that we update the document with all other wording changes (that came via email and other sources of feedback). Then together with MitOst we decided that this will be the final wording change (for the foreseeable future) and then we fix the remaining issues.

**Comment by gereonrahnfeld** [comment]
I agree, we need the final version first before we can finish this task. Therefore I propose to close this issue and reopen when needed. I will also close the US and we have a new one as soon as MitOst comes back to us.
