### ISSUE TITLE
Error messages in short idea sketch in German

### ISSUE THREAD

**Issue by rukala** [liqd/a4-advocate-europe#57]
The error messages in short idea sketch are in German.
![bildschirmfoto 2017-05-11 um 11 54 23](https://cloud.githubusercontent.com/assets/11075214/25943620/c58ff32a-3640-11e7-9e9e-bba3eff6c486.png)

**Comment by fuzzylogic2000** [comment]
Error messages should be in English now?!

**Comment by slomo** [comment]
Should be fixed on [a3-dev](https://ae-dev.liqd.net)
