### ISSUE TITLE
Error messages image size incorrect

### ISSUE THREAD

**Issue by rukala** [liqd/a4-advocate-europe#59]
When trying to upload an image which is too large, the error message has a tiny mistake ;) it says 3000
![bildschirmfoto 2017-05-11 um 12 09 48](https://cloud.githubusercontent.com/assets/11075214/25944245/e874acee-3642-11e7-8e9e-dea2cbbdab0b.png)
000 MB instead of 3MB.

**Comment by fuzzylogic2000** [comment]
I don't know how to fix that. It comes from A4:
./lib/python3.5/site-packages/adhocracy4/images/validators.py:        msg = _('Image should be at most {max_size} MB')

**Comment by slomo** [comment]
Added pull-request https://github.com/liqd/adhocracy4/pull/94, waiting to be merged.
