### ISSUE TITLE
Change text of activation tile

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#593]
Christina told me that they would like to have the text of the activation tile changed (just a little bit).

New text reads as follows:
_______________________________________________
Got an idea? Share it!

Apply now and get funding for your project Read about the criteria

Button:

Create your idea sketch

**Comment by fuzzylogic2000** [comment]
I think, with the short text it doesn't look as good (especially on tablet size). Also, we shouldn't add to this milestone anymore. But I changed the wording anyway!
