### ISSUE TITLE
view wording changes in advocate europe

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#603]
Please implement the following text changes:

 

Für 1)
Change the text to:

![nr 1](https://user-images.githubusercontent.com/15954895/33375469-485b8004-d50a-11e7-92aa-029202465241.jpg)

Do you want to collaborate on “x”?

If you accept you will be able to edit the idea and appear as a team member in the proposal. You can edit the text altogether until the application deadline.

Proceed to login

 

 

Für 2)
Change the text to: 

![nr 2](https://user-images.githubusercontent.com/15954895/33375496-61a1b042-d50a-11e7-9747-df68d862ec65.jpg)

Do you want to collaborate on “x”?

If you accept you will be able to edit the idea and appear as a team member in the proposal. You can edit the text altogether until the application deadline.

Accept / Decline

**Comment by fuzzylogic2000** [comment]
If we didn't do this yet, it is outdated and obsolete.
