### ISSUE TITLE
Idea sketch: Textareas are too small

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-advocate-europe#62]
The textarea for the idea sketchpitch will normally contain several lines of text. I would propose making it 300% higher than it is now per default. 

![bildschirmfoto 2017-05-11 um 17 44 27](https://cloud.githubusercontent.com/assets/15341015/25958718/b12e6a2a-3671-11e7-943a-c12ae745b3b3.png)

Same goes for all the textareas on this page:
![bildschirmfoto 2017-05-11 um 17 52 55](https://cloud.githubusercontent.com/assets/15341015/25959027/ba6a1eb2-3672-11e7-82aa-43781e259732.png)

**Comment by slomo** [comment]
They are by default 10 rows high, but there was some css quirk forcing them to be smaller removed it in 927f85efdd48dfb5c0f2d4a837d6632f0c54ab0e, which is currently beeing deployed. In case that they are to high now, please reopen.
