### ISSUE TITLE
no error shown when character limit is exceeded

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#628]
In AE we have the problem that users want to comment and answer comments with more than 1024 characters. If they do so there is no indication that the problem is them exceeding the character limit. If we do not extend the character limit we should at least give users an idea of what has happend and thus an error note that they exceeded the character limit. 

"Your post couldn't be displayed. It exceeded the limit of 1024 characters."

Something like that.

**Comment by gereonrahnfeld** [comment]
on ae dev error messages already exist

![screen shot 2017-12-19 at 17 41 21](https://user-images.githubusercontent.com/15954895/34168150-0f85df1a-e4e4-11e7-8cf5-9926a5e7ed19.png)

![screen shot 2017-12-19 at 17 41 35](https://user-images.githubusercontent.com/15954895/34168156-12dd1af2-e4e4-11e7-8466-c2f03d4696c8.png)

on ae stage they are missing

however, it should be mentioned what the reason is for the error.

**Comment by MagdaN** [comment]
should be fixed with https://github.com/liqd/adhocracy4/pull/230

**Comment by fuzzylogic2000** [comment]
fixed!
