### ISSUE TITLE
Idea sketch: Keep the original text even if too long

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-advocate-europe#65]
If I post a text in a textarea that is too long, the text is cut short to the max. no. of chars when the pages loads with the error messages. This could lead to a lot of frustration for people who entered long texts. Please keep the original text. Since the (very helpful!) error message states how many characters my text is beyond the limit, it will be easy for me to fix.

![bildschirmfoto 2017-05-11 um 17 55 12](https://cloud.githubusercontent.com/assets/15341015/25959208/4e17da1e-3673-11e7-92ee-bad52db448aa.png)

**Comment by slomo** [comment]
Can not reproduce.
