### ISSUE TITLE
Idea Page: Tabs are too small

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-advocate-europe#66]
For me, the tabs (Creators | Idea) on the idea detail page are very small and hard to notice. I overlooked them twice. The “watch“ and “share” buttons are much more noticeable. Can we emphasize the tabs somehow?

![bildschirmfoto 2017-05-11 um 17 59 38](https://cloud.githubusercontent.com/assets/15341015/25959421/d35b0354-3673-11e7-9d8e-9ef853e8960d.png)

**Comment by rittermo** [comment]
Any idea, @damusp ?

**Comment by damusp** [comment]
This was also mentioned by @rukala earlier here: https://zpl.io/ZRJeqj

I increased the font size a little bit here, but maybe the Tabs need even more emphasis. I'll be back with an alternative design!

**Comment by damusp** [comment]
So, here's a different design that tries to give everything better balance!

![idea_desktop_01](https://cloud.githubusercontent.com/assets/22769111/26006225/ed71881c-373b-11e7-9c34-12081945e959.png)

**Comment by rittermo** [comment]
Much nicer tabs, the low contrast between text and background for the inactive tab could be a little problematic. Apart from that, this looks great. :)

**Comment by rittermo** [comment]
Oh, one thing I just noticed. Currently, in the aside, the pitch is shown not the collaborators (https://ae-dev.liqd.net/de/ideas/magdas-idee/). Is that correct?

**Comment by damusp** [comment]
1) thanks! yeah, the contrast doesn't meet any accessibility standard at all… I'll change it!
2) No, actually it should be the exact opposite! The pitch should be only shown in the main content area.

**Comment by slomo** [comment]
Currently collaborators are show, if they [exist](https://ae-dev.liqd.net/en/ideas/magdas-idee/). Removing the pitch was already discussed offline, we can do it with the other design changes.

**Comment by damusp** [comment]
Hm, I think that even if there is only a single person involved (which is by definition not someone that collaborates) we should show the information anyway.

**Comment by MagdaN** [comment]
I close this as the tabs have been adapted to new design. I created an issue to alway display the creator in the collaborators list: https://github.com/liqd/a4-advocate-europe/issues/110
