### ISSUE TITLE
Idea detail page: Header area needs changes on small screen

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-advocate-europe#67]
On a small screen (320px width) the header of the idea needs a little fixing:

- the buttons (for watch and share) break in separate lines in a strange way and look strange with the tabs
- the labels for the are gone and I think it is really hard to guess what’s behind the buttons just from the icons
- the font size of the idea title is smaller than „Idea“, although the title is more important than the generic „title“ headline

https://ae-dev.liqd.net/de/ideas/bakery-in-the-clouds/#

![bildschirmfoto 2017-05-11 um 18 08 27](https://cloud.githubusercontent.com/assets/15341015/25959834/4f923cb6-3675-11e7-86b8-c888efa3250c.png)

**Comment by rittermo** [comment]
Could you take a look, @damusp ? As for the tabs, that might be linked with #66

**Comment by slomo** [comment]
Allegedly this could be fixed by switching to the correct font, but I am very sceptical that this will a stable solution.

**Comment by damusp** [comment]
I've been thinking about this. Here's what I've come up with so far:

![oldenew](https://cloud.githubusercontent.com/assets/22769111/26006076/739a420e-373b-11e7-9980-8a2822dbb9de.png)

Also take a look at the related design for desktop in #66

**Comment by rittermo** [comment]
Quick thoughts:

- The buttons look really sharp and much more usable to me now! I actually think that the “more” label should be present on large screens as well
- I am still not convinced that the generic title “idea needs” to be more emphasized than the actual title of the idea (“Thumbs of Europe“). Is ist also correct that the little excerpt that is shown on large screens is not shown here? I think these are a lot of constraints that happen when text is placed on top of images.

**Comment by damusp** [comment]
Thanks, I agree with both points. It's true, the idea-title is way too huge here!

About the little excerpt:
As designers tend to hide things away when they don't know what to do with them, this one just disappeared (it's a bad habit). In this case I think it might be actually benefitial for the user to hide it, but we can still just show it if we decide it's necessary.

**Comment by slomo** [comment]
@damusp Looks rather like a big change, could you also sketch if and how it affects the detail view for tablets and large screens?

**Comment by damusp** [comment]
hey @slomo, the design for larger screens is discussed here: #66 

From my perspective the changes are a large and satisfying improvement, but I can see that they mean a lot of unexpected additional work… Whaddaya think?

**Comment by damusp** [comment]
@slomo @gereonrahnfeld 
hej hej, the idea detail looks still messy on mobile.

do you think my [design](https://zpl.io/ZiGbNg) is feasible or should I try to find something else?

**Comment by gereonrahnfeld** [comment]
@damusp @slomo I definitely think it is worth it and that we should change it at one point. However, it is difficult for me to estimate the effort for it as well as for alternatives..  @slomo ?
