### ISSUE TITLE
Unclear use for checkbox 

### ISSUE THREAD

**Issue by philli-m** [liqd/a4-advocate-europe#766]
![advocate europe](https://user-images.githubusercontent.com/5871230/41856842-5ab74db6-7896-11e8-9e5b-d78a5184cbfd.png)

**Comment by MagdaN** [comment]
@phillimorland this happens if you don't set a page for 'terms of use' in the settings of wagtail, to add a page here, you need to go to wagtail and then settings and then help pages (I think)
