### ISSUE TITLE
Include placeholder texts in idea sketch form

### ISSUE THREAD

**Issue by rukala** [liqd/a4-advocate-europe#77]
A suggestion for even better understanding of the idea sketch form was to include placehoder texts in the input fields to show users what kind of input is expected from them (e.g. emails seperated by commas, etc.).

**Comment by slomo** [comment]
@damusp I would be interested in your opinion.

For me the main issue is that I can't come up with meaning full placeholders for most fields (eg, IdeaPitch, IdeaTitle, IdeaText, etc). Also using labels, placeholders and help texts seems to be a bit overkill.

Maybe we should improve the help text of specific fields instead? Or only provide placeholders for a few selected fields? The latter probably looks a bit odd.

**Comment by damusp** [comment]
I agree with @slomo here. 
- Placeholders can be nice and quite helpful, but in our wizard this would be indeed over the top. 
- I'm for improving the help texts as well.

**Comment by rukala** [comment]
@slomo : I think the idea with placeholder texts was meant for "functional" fields such as email address fields - I think it would be great to include them in a selected few fields. I can check which ones.

@damusp : we have to briefly run changes in the help texts by MitOst

**Comment by MagdaN** [comment]
@rukala @slomo @damusp I think it would make sense in some fields e.g. collaborators where a list of email addresses is exspected

**Comment by fuzzylogic2000** [comment]
@gereonrahnfeld @rukala @damusp Are we happy with the help texts and no placeholder-texts like they currently are?

**Comment by damusp** [comment]
I'm happy – what do you guys think?

**Comment by gereonrahnfeld** [comment]
I am happy as well.

**Comment by fuzzylogic2000** [comment]
And I am happy to close this issue!
