### ISSUE TITLE
Distinct submit button for final submission of idea sketch

### ISSUE THREAD

**Issue by rukala** [liqd/a4-advocate-europe#78]
It would be great to include a distinct submit button on the last page of the idea sketch form in order to show users that they are finally submitting all their input. In addition to the email which is then triggered to the users perhaps we can show a notification in the UI which explains that all infos have been saved but that they can be edited until the final submission deadline.

**Comment by slomo** [comment]
@damusp Currently we only have two button styles (blue and yellow). Should we use one of them for that purpose or create a new one?

@rukala A notification can be implemented. It should have concise wording. Would the text below be acceptable.

> Successfully save your {proposal|idea sketch}. You can edit it until final submission deadline {date}.

**Comment by rukala** [comment]
@slomo : sounds good! Perhaps we don't need the "successfully" - I think the sentence on the submission deadline is very clear.

**Comment by damusp** [comment]
a distinct submit button that stands out a bit seems like a good idea to me. 

I wouldn't introduce a new color though, instead I suggest making this special button bigger:

![wizardbuttons](https://cloud.githubusercontent.com/assets/22769111/26636303/9d34d33c-461c-11e7-85c8-af3ec3ecfd47.png)

**Comment by fuzzylogic2000** [comment]
I made the button bigger, but think it looks rather strange now?!
![bildschirmfoto vom 2017-06-02 14-02-08](https://cloud.githubusercontent.com/assets/8178179/26724921/17f8f514-479c-11e7-8c5e-8f7b7ad3c5a7.png)

**Comment by damusp** [comment]
@rukala @fuzzylogic2000 hm, right, that does indeed look quite poor. 

It has just come to my mind that we were thinking about a final "finish" step. How about something like this: 


![finish](https://cloud.githubusercontent.com/assets/22769111/26726965/40ed28e2-47a5-11e7-95a6-e9ae6414e24b.png)
