### ISSUE TITLE
reenable whitenoise

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-advocate-europe#824]
@treba123 I had to revert https://github.com/liqd/a4-advocate-europe/commit/03fd963ead44c0e1b8697cc426bf8001572f1c9e to fix master.
My first attempt was to add whitenoise to the rquirements, but it was still failing. We should come back to that when the other problem is fixed. 

P.S.: it's a good idea to make a PR and wait for travis if you do stuff to lately not so very maintained projects

**Comment by fuzzylogic2000** [comment]
Oh no, it's something else. Still failing.

**Comment by fuzzylogic2000** [comment]
Well it was that commit and whitenoise! But adding it to the requirements (and running test-clean) did actually fix it.

**Comment by rmader** [comment]
Oouch! Yeah I took the quick road to finally fix that on all projects....somehow missed that :(
Thanks for fixing this!
