### ISSUE TITLE
Not possible to edit JOIN / MITMACHEN section in wagtail

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-advocate-europe#898]
Christina told me last week that they cannot edit the join / mitmachen section in wagtail anymore. However, they would like to edit soonish. 
@MagdaN could you have a look please?

**Comment by MagdaN** [comment]
I guess this is this error here: https://github.com/wagtail/wagtail/issues/4602

I checked our db but the streamfields are too clustered, to remove the `<b>` tags manually, so I think we have to do a substring replacement on the db level or downgrade wagtail again.

@treba123 it would be great if we could do that together
