### ISSUE TITLE
What additional information needs to be displayed for full proposal e.g. budget and where

### ISSUE THREAD

**Issue by MagdaN** [liqd/a4-advocate-europe#97]
In google docs it says, information on budget are public, is that right @rukala? @damusp, where in the designs should we display this?

**Comment by rukala** [comment]
@MagdaN this is the current info I have from the google doc - I will double check with MitOst

**Comment by fuzzylogic2000** [comment]
The selection criteria are also public and only exist in the proposal

**Comment by MagdaN** [comment]
@damusp can you prepare designs for this please?

**Comment by fuzzylogic2000** [comment]
@MagdaN That's solved, right?

**Comment by MagdaN** [comment]
yup
